name: Build & release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: npm i
        
      - name: "Build"
        run: npm run build:appx

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*.appx"
          allowUpdates: true
          draft: true
          generateReleaseNotes: true
